[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "Cython < 3.1.0",
    "py-cpuinfo",
    "setuptools",
    "wheel",
    ]

[tool.pytest.ini_options]
addopts = "-s --doctest-modules"
testpaths = [
    "src",
    "tests",
    ]

[tool.cibuildwheel]
test-requires = "pytest"
